# Generated by Django 5.2.1 on 2025-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='shape',
            field=models.CharField(choices=[('CIRCLE', 'Circle'), ('SQUARE', 'Square'), ('TRIANGLE', 'Triangle')], max_length=20),
        ),
    ]
